# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NWHacks' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NWHacks
  pod 'Alamofire'
  pod 'AppCenter'
  target 'NWHacksTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NWHacksUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
