# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BeginnerTableView' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'QRCodeReader.swift', '~> 10.0.0'

  pod 'Alamofire'
  pod 'AppCenter'
  pod 'Kingfisher', '~> 5.0'
  pod 'AppCenter/Push'
 
  # Pods for BeginnerTableView

end
